### PR TITLE
added survey results for jun 2013 railsbridge Boston event

### PR DESCRIPTION
**Pull request by toddp**
added static files from google doc survey results under /public

### CODE REVIEW

**Comment by drapergeek** [comment]
I think it would be nice if we could clean this up and just put it into a normal HTML page instead of using the google docs import look.

I think in the past we have just put the information into the 'recap' for the workshop and I personally like that idea.

That being said if you could share out the results, I would appreciate that. jason@drapergeek.com please.

**Comment by toddp** [comment]
hi Jason, yes I was wondering whether this would be too ugly; however I was also trying to follow what Braulio asked and get his feedback on this also. If the consensus is to clean it up, I can do that.

**Comment by drapergeek** [comment]
Oh most definitely, I'm just tossing in an opinion.

**Comment by bcarreno** [comment]
I think @drapergeek has a valid point.  When I published the survey results for the first time (1 year ago) I didn't have much time and did the dirty export.  From that point I was lazy and kept doing the same thing.

I'm going to push the changes and next time we can do something better.  We have result for 5 workshops that we could keep in a better format if we wanted to.

Note that the recap always goes with the first graph only: "How do you rate the RailsBridge Boston Workshop?" @dylancashman is working on that.

**Pull request merged**
