### PR TITLE
Break homepage content into separate pages

### PR DESCRIPTION
**Pull request by mxie**
- Moved About content and photos into an About page.
- Moved recap links to a Blog page.

### CODE REVIEW

**Comment by mxie** [comment]
Also decided to move the About content as well. See the screenshots below for the new look:

Homepage:
railsbridge boston 2013-12-27 22-45-21

About page:
railsbridge boston 2013-12-27 22-46-11

Blog/recaps page:
railsbridge boston 2013-12-27 22-46-37

Any thoughts on this "redesign/refactor", @janetriley?

**Comment by drapergeek** [comment]
How about adding a link to the last workshop recap on the front page? I think you may be pulling that a little too far away from the 'average' viewer.

**Comment by drapergeek** [comment]
Looks good otherwise.

**Comment by janetriley** [comment]
I like it a lot.   The front page needed to be streamlined, and "About" pages are usually the most-visited on a site after the homepage.

-- 
Janet Riley
jriley@janetriley.net
857-288-8428

On December 27, 2013 at 10:47:32 PM, Melissa Xie (notifications@github.com) wrote:

Also decided to move the About content as well. See the screenshots below for the new look:

Homepage:

About page:

Blog/recaps page:

Any thoughts on this "redesign/refactor", @janetriley?

**Comment by mxie** [comment]
New screenshot where I made the CTA more distinct (it's not very pretty, but it's something?), emphasizing more on registration instead of becoming a TA or organizer:

railsbridge boston 2013-12-29 23-28-01

**Comment by mxie** [comment]
@drapergeek @janetriley Further thoughts based on the screenshot above?

**Pull request merged**
