### PR TITLE
Update versions: VM (2014-05), Vagrant (1.6.1), VirtualBox (4.3.10), ruby (2.0.0p451)

### PR DESCRIPTION
**Pull request by decklin**
Ubuntu 14.04!

The final box file referred to here is not built yet. Please download this RC and test:

http://downloads.railsbridge.org/railsbridgevm-2014-05-rc1.box

with the new Virtualbox/Vagrant versions.

### CODE REVIEW

**Comment by decklin** [comment]
I renamed the VM repo to: https://github.com/railsbridge-boston/railsbridge-vm

and pushed updates there. Please delete/rebase any branches you had.

**Comment by decklin** [comment]
Updated link (built new RC): http://downloads.railsbridge.org/railsbridgevm-2014-05-rc2.box

**Comment by decklin** [comment]
New build... last call to get anything else in! http://downloads.railsbridge.org/railsbridgevm-2014-05-rc3.box

**Comment by janetriley** [comment]
The heroku setup page (http://www.railsbridgeboston.org/installfest/create_a_heroku_account)  asks for the heroku and gittyup gems.  It would be swell to have them included, but no big deal if not.

The heroku gem notes that it's deprecated and the heroku toolbelt is preferred.

**Comment by decklin** [comment]
Yeah, I think we should update that page to recommend installing the toolbelt.

**Comment by decklin** [comment]
OK, I rebased this on master (looks like an -rc URL got merged into master, with a wrong filename).

**Pull request merged**
