### PR TITLE
Add .ruby-version and (for rvm) .ruby-gemset to .gitignore.

### PR DESCRIPTION
**Pull request by houhoulis**

### CODE REVIEW

**Comment by drapergeek** [comment]
Why would we ignore those files? They are nice to have for being able to verify which ruby version the app runs on.

**Comment by houhoulis** [comment]
I agree there is benefit to including the files in the repo.  But the flipside is that they require the developer to use a version of Ruby they may not have installed locally.  (Plus, if using rvm, `.ruby-gemset` forces use of a gemset, of a particular name.)

I am just trying to follow what I see as the convention here.  `.rbenv-version` (an older version of the universal `.ruby-version` file) is already in the .gitignore, so I added `.ruby-version` and `.ruby-gemset` to .gitignore as well, to be consistent.  The files were not already in the repo, and I wanted to avoid adding them.

**Comment by patricksrobertson** [comment]
I would say that the existing convention in the application is going against the Ruby best practice about being explicit on which version of Ruby you are using and change it.

**Comment by houhoulis** [comment]
I opened [pull request 49](https://github.com/railsbridge-boston/railsbridge-boston/pull/49) in accordance with Patrick's feedback.  Either one works for me.

**Comment by danchoi** [comment]
If we need to require a certain version of Ruby, maybe we should just specify the Ruby version in the Gemfile, since that's what Heroku actually uses. 

http://gembundler.com/v1.2/whats_new.html
https://devcenter.heroku.com/articles/ruby-versions 

I didn't know it was convention or best practice to add rbenv and rvm specific dotfiles to Ruby projects. If that's actually the case I don't mind people changing the repo to reflect that.

**Pull request merged**
